version: '3'
services:
  mariadb:
    build: ./requirements/mariadb/
    image: mariadb
    container_name: mariadb
    restart:
      always
    volumes:
      - ../data/mysql:/var/lib/mysql
    networks:
      - aalfahal-inception
    env_file:
      - .env
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/
    image: wordpress
    depends_on:
      - mariadb
    volumes:
      - web_data:/usr/share/webapps/wordpress
    networks:
      - aalfahal-inception
    restart: on-failure
    env_file:
      - .env
  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    image: nginx
    depends_on:
      - mariadb
      - wordpress
    volumes:
      - web_data:/var/www/html/wordpress
    networks:
      - aalfahal-inception
    ports:
      - "80:80"
    restart: on-failure
    env_file:
      - .env
    init: true

networks:
  aalfahal-inception:

volumes:
  web_data:
    driver: local
    driver_opts:
      type: none
      device: /Users/ahmedalfahal/Desktop/Inception/data/wordpress
      o: bind