version: '3'
services:
  mariadb:
    build: ./requirements/mariadb/
    image: mariadb
    container_name: mariadb
    restart:
      on-failure
    volumes:
      - ~/data/mysql:/var/lib/mysql
    networks:
      - aalfahal-inception
    secrets:
      - MARIADB_ROOT_USER
      - MARIADB_ROOT_PASSWORD
      - DB_NAME
      - DB_USER
      - DB_PASS
      - domain
  wordpress:
    build: ./requirements/wordpress/
    image: wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    volumes:
      - wp_data:/var/www/html/wordpress
    networks:
      - aalfahal-inception
    restart:
      on-failure
    secrets:
      - DB_NAME
      - DB_USER
      - DB_PASS
      - WP_AMDIN_USER
      - WP_ADMIN_PASS
      - WP_USER
      - WP_PASS
      - domain
  nginx:
    build: ./requirements/nginx/
    image: nginx
    container_name: nginx
    depends_on:
      - mariadb
      - wordpress
    volumes:
      - wp_data:/var/www/html/wordpress
    networks:
      - aalfahal-inception
    ports:
      - "443:443"
    restart:
      on-failure
    secrets:
      - nginx_cert
      - nginx_cert_key
      - domain

networks:
  aalfahal-inception:

secrets:
  MARIADB_ROOT_USER:
   file: ../secrets/mariadb_root_user.txt
  MARIADB_ROOT_PASSWORD:
   file: ../secrets/mariadb_root_password.txt
  DB_NAME:
   file: ../secrets/db_name.txt
  DB_USER:
    file: ../secrets/db_username.txt
  DB_PASS:
    file: ../secrets/db_password.txt
  WP_AMDIN_USER:
    file: ../secrets/wp_admin_user.txt
  WP_ADMIN_PASS:
    file: ../secrets/wp_admin_pass.txt
  WP_USER:
    file: ../secrets/wp_username.txt
  WP_PASS:
    file: ../secrets/wp_password.txt
  nginx_cert:
    file: ../secrets/cert.crt
  nginx_cert_key:
    file: ../secrets/cert.key
  domain:
    file: ../secrets/domain.txt

volumes:
  wp_data:
    driver: local
    driver_opts:
      type: none
      device: ~/data/wordpress
      o: bind
