version: '3'
services:
  mariadb:
    build: ./requirements/mariadb/
    image: mariadb
    container_name: mariadb
    restart:
      always
    volumes:
      - ./requirements/mariadb:/app/mariadb
    networks:
      - aalfahal-inception
    env_file:
      - .env
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/
    image: wordpress
    depends_on:
      - mariadb
    volumes:
      - ./requirements/wordpress:/usr/share/webapps/
    networks:
      - aalfahal-inception
    restart: on-failure
    env_file:
      - .env
  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    image: nginx
    depends_on:
      - mariadb
      - wordpress
    volumes:
      - ./requirements/nginx:/app/nginx
    networks:
      - aalfahal-inception
    ports:
      - "443:443"
    restart: on-failure
    env_file:
      - .env
    init: true

networks:
  aalfahal-inception: